import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";
// import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});

const JetBrainsMono_bold = localFont({
  src: "../public/fonts/JetBrainsMono-Bold.woff2",
  variable: "--font-JetBrainsMono_bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "...",
    description: "...",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body className={JetBrainsMono_bold.variable}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">
            {/* <Suspense fallback={<p>Loading...</p>}>{children}</Suspense> */}
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
