"use client";
import Image from "next/image";
import coffee from "@/public/images/example.png";
import Link from "next/link";
import ProductCard from "./components/ProductCard";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Metadata } from "next";

import { useState } from "react";
import dynamic from "next/dynamic";
// import _ from "lodash";
const HeavyComponent = dynamic(() => import("./components/HeavyComponent"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

// export default async function Home() {
//   const session = await getServerSession(authOptions);
//   return (
//     <main>
//       <h1>Hello {session && <span>{session.user!.name}</span>}</h1>
//       <Link href="/users">Users</Link>
//       <ProductCard />
//       <Image src={coffee} alt="cofee" priority />
//       <div className="relative h-screen">
//         <Image
//           src="https://picsum.photos/seed/picsum/200/300"
//           alt="cofee"
//           // width={300}
//           // height={200}
//           fill
//           className="object-contain"
//           // sizes="100vw"
//           sizes="(max-width:480px) 100vw, (max-width:768px) 50vw, 33vw"
//           quality={100}
//           priority
//         />
//       </div>
//     </main>
//   );
// }

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   openGraph: {
//     title: "...",
//     description: "...",
//   },
// };

// export async function generateMetadata(): Promise<Metadata> {
//   const product = await fetch("");
//   return {
//     title: "product.title",
//     description: "product.description",
//   };
// }

export default function Home() {
  const [isVisible, setVisible] = useState(false);
  return (
    <main>
      <h1>Hello World</h1>
      <button onClick={() => setVisible(true)}>Show</button>
      {isVisible && <HeavyComponent />}
      <br />
      <button
        onClick={async () => {
          const _ = (await import("lodash")).default;
          const users = [{ name: "c" }, { name: "b" }, { name: "a" }];

          const sorted = _.orderBy(users, ["name"]);
          console.log(sorted);
        }}
      >
        Show
      </button>
    </main>
  );
}
